<a href="https://colab.research.google.com/github/ShyamSundhar1411/My-ML-Notebooks/blob/master/PyTorch/PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
print(torch.__version__)

2.0.1+cu118


## Introduction to tensors

### Creating tensors

In [3]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
#vector
vector = torch.tensor([7,10,7])
vector

tensor([ 7, 10,  7])

In [6]:
vector.ndim

1

In [15]:
#Matrix
matrix = torch.tensor([[7,8,10],
                       [9,10,10]
                       ])

In [16]:
matrix.ndim

2

In [17]:
matrix

tensor([[ 7,  8, 10],
        [ 9, 10, 10]])

In [18]:
matrix[0]

tensor([ 7,  8, 10])

In [12]:
matrix[1]

tensor([ 9, 10])

In [13]:
matrix.shape

torch.Size([2, 2])

In [20]:
#tensor
tensor = torch.tensor([[[1,3,4],[3,6,9],[2,4,5]

]])

In [21]:
tensor

tensor([[[1, 3, 4],
         [3, 6, 9],
         [2, 4, 5]]])

In [22]:
tensor.ndim

3

In [23]:
tensor.shape

torch.Size([1, 3, 3])

In [25]:
tensor_2 = torch.tensor([
    [
    [1,2,3],
    [3,4,5],
    [6,7,8],],
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
])

In [26]:
tensor_2[0]

tensor([[1, 2, 3],
        [3, 4, 5],
        [6, 7, 8]])

In [27]:
tensor_2[1]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [28]:
tensor_2.shape

torch.Size([2, 3, 3])

### Random Tensors

In [50]:
random_tensor = torch.rand(3,4)

In [39]:
random_tensor

tensor([[[0.3838, 0.6963, 0.8355, 0.8696, 0.2333],
         [0.0358, 0.3365, 0.8877, 0.2646, 0.7314],
         [0.2443, 0.6853, 0.5781, 0.8138, 0.2205],
         [0.9607, 0.1537, 0.0588, 0.6425, 0.8177]],

        [[0.4130, 0.4463, 0.1932, 0.6414, 0.8721],
         [0.7530, 0.5235, 0.9501, 0.7442, 0.0293],
         [0.0476, 0.8766, 0.1910, 0.2421, 0.6136],
         [0.6677, 0.6710, 0.9102, 0.1315, 0.4694]],

        [[0.5484, 0.4681, 0.0902, 0.5003, 0.3431],
         [0.1826, 0.9274, 0.2792, 0.2526, 0.1845],
         [0.4010, 0.3362, 0.1207, 0.8880, 0.9444],
         [0.3980, 0.2881, 0.1990, 0.4789, 0.3239]]])

In [40]:
random_tensor.shape

torch.Size([3, 4, 5])

In [41]:
random_tensor.ndim

3

In [42]:
random_image_tensor = torch.rand(size=(224,224,3))

In [43]:
random_image_tensor

tensor([[[0.8454, 0.3863, 0.6739],
         [0.7120, 0.5558, 0.6965],
         [0.9449, 0.9673, 0.3198],
         ...,
         [0.8787, 0.5542, 0.0657],
         [0.9146, 0.0171, 0.7747],
         [0.0608, 0.8768, 0.0752]],

        [[0.9712, 0.1906, 0.9997],
         [0.4891, 0.9193, 0.5575],
         [0.3314, 0.3199, 0.8507],
         ...,
         [0.9650, 0.3627, 0.5986],
         [0.1352, 0.9447, 0.1855],
         [0.4435, 0.1008, 0.5847]],

        [[0.7981, 0.8430, 0.2088],
         [0.4973, 0.1724, 0.7660],
         [0.1138, 0.1200, 0.7372],
         ...,
         [0.6220, 0.7999, 0.9001],
         [0.6890, 0.1873, 0.0211],
         [0.1446, 0.9605, 0.8270]],

        ...,

        [[0.7155, 0.5445, 0.9127],
         [0.3476, 0.2860, 0.9784],
         [0.4408, 0.9520, 0.6513],
         ...,
         [0.6901, 0.2062, 0.8567],
         [0.1001, 0.1435, 0.9655],
         [0.6431, 0.6736, 0.1232]],

        [[0.2309, 0.4017, 0.6762],
         [0.6970, 0.5026, 0.0016],
         [0.

In [44]:
random_image_tensor.ndim

3

In [45]:
random_image_tensor.shape

torch.Size([224, 224, 3])

### Zeros and Ones

In [47]:
zeros = torch.zeros(size=(3,4))

In [48]:
zeros


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [51]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [52]:
ones = torch.ones(size = (3,4))

In [53]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensors-like

In [55]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Tensor Datatypes

In [56]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype = None)

In [57]:
float_32_tensor.dtype

torch.float32

### Tensor Operations

In [65]:
 tensor = torch.tensor([1,2,3])
 tensor+10

tensor([11, 12, 13])

In [66]:
tensor*10

tensor([10, 20, 30])

In [67]:
tensor-10

tensor([-9, -8, -7])

In [68]:
tensor_2 = torch.tensor([1,2,5])
tensor_2-tensor

tensor([0, 0, 2])

In [69]:
torch.mul(tensor,tensor_2)

tensor([ 1,  4, 15])