<a href="https://colab.research.google.com/github/ShyamSundhar1411/My-ML-Notebooks/blob/master/PyTorch/PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
print(torch.__version__)

2.0.1+cu118


## Introduction to tensors

### Creating tensors

In [3]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
#vector
vector = torch.tensor([7,10,7])
vector

tensor([ 7, 10,  7])

In [6]:
vector.ndim

1

In [7]:
#Matrix
matrix = torch.tensor([[7,8,10],
                       [9,10,10]
                       ])

In [8]:
matrix.ndim

2

In [9]:
matrix

tensor([[ 7,  8, 10],
        [ 9, 10, 10]])

In [10]:
matrix[0]

tensor([ 7,  8, 10])

In [11]:
matrix[1]

tensor([ 9, 10, 10])

In [12]:
matrix.shape

torch.Size([2, 3])

In [13]:
#tensor
tensor = torch.tensor([[[1,3,4],[3,6,9],[2,4,5]

]])

In [14]:
tensor

tensor([[[1, 3, 4],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
tensor.ndim

3

In [16]:
tensor.shape

torch.Size([1, 3, 3])

In [17]:
tensor_2 = torch.tensor([
    [
    [1,2,3],
    [3,4,5],
    [6,7,8],],
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
])

In [18]:
tensor_2[0]

tensor([[1, 2, 3],
        [3, 4, 5],
        [6, 7, 8]])

In [19]:
tensor_2[1]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [20]:
tensor_2.shape

torch.Size([2, 3, 3])

### Random Tensors

In [21]:
random_tensor = torch.rand(3,4)

In [22]:
random_tensor

tensor([[0.4693, 0.1242, 0.5220, 0.1994],
        [0.3882, 0.6534, 0.0202, 0.8906],
        [0.3545, 0.9322, 0.7604, 0.0967]])

In [23]:
random_tensor.shape

torch.Size([3, 4])

In [24]:
random_tensor.ndim

2

In [25]:
random_image_tensor = torch.rand(size=(224,224,3))

In [26]:
random_image_tensor

tensor([[[0.7865, 0.5812, 0.2893],
         [0.6190, 0.2816, 0.0640],
         [0.6883, 0.8200, 0.7726],
         ...,
         [0.1180, 0.9258, 0.4937],
         [0.2117, 0.8649, 0.5236],
         [0.2801, 0.2492, 0.7615]],

        [[0.0124, 0.5697, 0.5675],
         [0.6699, 0.7496, 0.3367],
         [0.5700, 0.4483, 0.7472],
         ...,
         [0.9462, 0.2357, 0.2341],
         [0.9490, 0.2638, 0.1433],
         [0.3998, 0.4776, 0.1100]],

        [[0.9471, 0.8049, 0.6441],
         [0.6772, 0.6155, 0.7472],
         [0.5900, 0.2749, 0.0955],
         ...,
         [0.7934, 0.5939, 0.4554],
         [0.6629, 0.7989, 0.7784],
         [0.1402, 0.3931, 0.9101]],

        ...,

        [[0.5461, 0.8704, 0.5654],
         [0.8545, 0.1504, 0.0273],
         [0.9185, 0.9879, 0.4992],
         ...,
         [0.0655, 0.3594, 0.6272],
         [0.8320, 0.2809, 0.3856],
         [0.7888, 0.9972, 0.2945]],

        [[0.4609, 0.5855, 0.4565],
         [0.8189, 0.6180, 0.6367],
         [0.

In [27]:
random_image_tensor.ndim

3

In [28]:
random_image_tensor.shape

torch.Size([224, 224, 3])

### Zeros and Ones

In [29]:
zeros = torch.zeros(size=(3,4))

In [30]:
zeros


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [31]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [32]:
ones = torch.ones(size = (3,4))

In [33]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensors-like

In [34]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Tensor Datatypes

In [35]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype = None)

In [36]:
float_32_tensor.dtype

torch.float32

### Tensor Operations

In [37]:
 tensor = torch.tensor([1,2,3])
 tensor+10

tensor([11, 12, 13])

In [38]:
tensor*10

tensor([10, 20, 30])

In [39]:
tensor-10

tensor([-9, -8, -7])

In [40]:
tensor_2 = torch.tensor([1,2,5])
tensor_2-tensor

tensor([0, 0, 2])

In [41]:
torch.mul(tensor,tensor_2)

tensor([ 1,  4, 15])

### Matrix Multiplication

In [42]:
matrix = torch.matmul(tensor,tensor_2)

In [43]:
matrix

tensor(20)

 ### Tensor Aggregation

In [44]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [45]:
torch.min(x),x.min()

(tensor(0), tensor(0))

In [46]:
torch.max(x),x.max()

(tensor(90), tensor(90))

In [47]:
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [48]:
x.argmax()

tensor(9)

In [49]:
x.argmin()

tensor(0)

## Reshaping, Stacking, Squeezing and Unsqueezing tensors

In [50]:
import torch
x = torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [52]:
x_reshaped = x.reshape(1,9)

In [53]:
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [54]:
x_reshaped = x_reshaped.reshape(9,1)

In [55]:
x_reshaped

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])