<a href="https://colab.research.google.com/github/ShyamSundhar1411/My-ML-Notebooks/blob/master/PyTorch/PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Fundamentals

In [87]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [88]:
print(torch.__version__)

2.0.1+cu118


## Introduction to tensors

### Creating tensors

In [89]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [90]:
scalar.ndim

0

In [91]:
#vector
vector = torch.tensor([7,10,7])
vector

tensor([ 7, 10,  7])

In [92]:
vector.ndim

1

In [93]:
#Matrix
matrix = torch.tensor([[7,8,10],
                       [9,10,10]
                       ])

In [94]:
matrix.ndim

2

In [95]:
matrix

tensor([[ 7,  8, 10],
        [ 9, 10, 10]])

In [96]:
matrix[0]

tensor([ 7,  8, 10])

In [97]:
matrix[1]

tensor([ 9, 10, 10])

In [98]:
matrix.shape

torch.Size([2, 3])

In [99]:
#tensor
tensor = torch.tensor([[[1,3,4],[3,6,9],[2,4,5]

]])

In [100]:
tensor

tensor([[[1, 3, 4],
         [3, 6, 9],
         [2, 4, 5]]])

In [101]:
tensor.ndim

3

In [102]:
tensor.shape

torch.Size([1, 3, 3])

In [103]:
tensor_2 = torch.tensor([
    [
    [1,2,3],
    [3,4,5],
    [6,7,8],],
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
])

In [104]:
tensor_2[0]

tensor([[1, 2, 3],
        [3, 4, 5],
        [6, 7, 8]])

In [105]:
tensor_2[1]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [106]:
tensor_2.shape

torch.Size([2, 3, 3])

### Random Tensors

In [107]:
random_tensor = torch.rand(3,4)

In [108]:
random_tensor

tensor([[0.6688, 0.2014, 0.6027, 0.7800],
        [0.3469, 0.6540, 0.0338, 0.0386],
        [0.6755, 0.5566, 0.8210, 0.1741]])

In [109]:
random_tensor.shape

torch.Size([3, 4])

In [110]:
random_tensor.ndim

2

In [111]:
random_image_tensor = torch.rand(size=(224,224,3))

In [112]:
random_image_tensor

tensor([[[0.7595, 0.3127, 0.2514],
         [0.2580, 0.7035, 0.6351],
         [0.7879, 0.8984, 0.5558],
         ...,
         [0.1991, 0.5854, 0.8017],
         [0.5963, 0.0536, 0.1748],
         [0.4713, 0.8191, 0.9957]],

        [[0.4740, 0.1956, 0.3586],
         [0.6667, 0.7320, 0.5626],
         [0.3372, 0.1662, 0.7335],
         ...,
         [0.1656, 0.1128, 0.0664],
         [0.7207, 0.1615, 0.4191],
         [0.8452, 0.3531, 0.7131]],

        [[0.5532, 0.3422, 0.2639],
         [0.1104, 0.6605, 0.1722],
         [0.5349, 0.9078, 0.7730],
         ...,
         [0.1848, 0.2103, 0.8359],
         [0.7659, 0.0158, 0.8617],
         [0.7077, 0.5775, 0.3744]],

        ...,

        [[0.9608, 0.6652, 0.6938],
         [0.9454, 0.0293, 0.1906],
         [0.5998, 0.5150, 0.4732],
         ...,
         [0.5984, 0.9894, 0.3989],
         [0.7018, 0.7123, 0.2903],
         [0.6356, 0.2267, 0.7375]],

        [[0.6494, 0.7414, 0.6765],
         [0.7588, 0.7140, 0.6524],
         [0.

In [113]:
random_image_tensor.ndim

3

In [114]:
random_image_tensor.shape

torch.Size([224, 224, 3])

### Zeros and Ones

In [115]:
zeros = torch.zeros(size=(3,4))

In [116]:
zeros


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [117]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [118]:
ones = torch.ones(size = (3,4))

In [119]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensors-like

In [120]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Tensor Datatypes

In [121]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype = None)

In [122]:
float_32_tensor.dtype

torch.float32

### Tensor Operations

In [123]:
 tensor = torch.tensor([1,2,3])
 tensor+10

tensor([11, 12, 13])

In [124]:
tensor*10

tensor([10, 20, 30])

In [125]:
tensor-10

tensor([-9, -8, -7])

In [126]:
tensor_2 = torch.tensor([1,2,5])
tensor_2-tensor

tensor([0, 0, 2])

In [127]:
torch.mul(tensor,tensor_2)

tensor([ 1,  4, 15])

### Matrix Multiplication

In [128]:
matrix = torch.matmul(tensor,tensor_2)

In [129]:
matrix

tensor(20)

 ### Tensor Aggregation

In [130]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [131]:
torch.min(x),x.min()

(tensor(0), tensor(0))

In [132]:
torch.max(x),x.max()

(tensor(90), tensor(90))

In [138]:
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(45.), tensor(45.))