In [9]:
import tensorflow as tf
import numpy as np


## *Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().*

In [5]:
tensor1 = tf.constant([10,7])
tensor1.shape,tf.rank(tensor1),tf.size(tensor1)

(TensorShape([2]),
 <tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>)

In [6]:
tensor2 = tf.constant([[[
    [10,7,8],
    [9,12,3],
]]])
tensor2.shape,tf.rank(tensor2),tf.size(tensor2)

(TensorShape([1, 1, 2, 3]),
 <tf.Tensor: shape=(), dtype=int32, numpy=4>,
 <tf.Tensor: shape=(), dtype=int32, numpy=6>)

## *Create two tensors containing random values between 0 and 1 with shape [5, 300].*

In [20]:
generator = tf.random.Generator.from_seed(42)
tensor3 = generator.uniform(shape = (5,300))
tensor4 = generator.uniform(shape = (5,300))

In [21]:
tensor3

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.7493447 , 0.73561966, 0.45230794, ..., 0.5816356 , 0.5627874 ,
        0.7491298 ],
       [0.6438937 , 0.6938418 , 0.04408407, ..., 0.04825139, 0.5099728 ,
        0.26470542],
       [0.21373153, 0.6683699 , 0.78474844, ..., 0.19658887, 0.22030771,
        0.3766911 ],
       [0.68190825, 0.29304636, 0.5415933 , ..., 0.37111604, 0.76053166,
        0.7538099 ],
       [0.8011551 , 0.48830473, 0.13867617, ..., 0.20301867, 0.8378159 ,
        0.19984365]], dtype=float32)>

In [22]:
tensor4

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.6932683 , 0.79913497, 0.381521  , ..., 0.7023829 , 0.9509897 ,
        0.2274468 ],
       [0.03644454, 0.6579336 , 0.27609527, ..., 0.6680317 , 0.42852902,
        0.17845905],
       [0.28606403, 0.3063997 , 0.25755703, ..., 0.6562083 , 0.7018373 ,
        0.76578414],
       [0.71172917, 0.7854034 , 0.6951294 , ..., 0.03848457, 0.6082274 ,
        0.23704243],
       [0.40945458, 0.49275637, 0.46033657, ..., 0.06898165, 0.74632454,
        0.56117034]], dtype=float32)>

In [24]:
## *Multiply the two tensors you created in 3 using matrix multiplication*

In [25]:
tf.matmul(tensor3,tf.transpose(tensor4))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[76.06833 , 73.937325, 79.660126, 72.81196 , 80.260735],
       [73.6188  , 69.42696 , 73.688484, 67.240585, 72.29571 ],
       [72.672356, 73.27016 , 73.097145, 70.96236 , 72.99701 ],
       [75.63145 , 73.94715 , 75.9094  , 72.79953 , 75.46771 ],
       [76.59263 , 73.6522  , 77.3451  , 68.49896 , 77.61455 ]],
      dtype=float32)>

In [29]:
tf.tensordot(tensor3,tf.transpose(tensor4),axes = 0)

<tf.Tensor: shape=(5, 300, 300, 5), dtype=float32, numpy=
array([[[[0.5194969 , 0.02730953, 0.21436056, 0.5333305 , 0.30682263],
         [0.59882754, 0.49301904, 0.229599  , 0.5885379 , 0.36924437],
         [0.28589073, 0.20689052, 0.192999  , 0.52089155, 0.34495077],
         ...,
         [0.52632695, 0.50058603, 0.4917262 , 0.02883821, 0.05169103],
         [0.7126191 , 0.32111597, 0.52591807, 0.45577195, 0.55925435],
         [0.17043605, 0.13372734, 0.57383627, 0.17762649, 0.42051002]],

        [[0.5099818 , 0.02680932, 0.21043432, 0.52356195, 0.30120283],
         [0.5878594 , 0.48398888, 0.22539365, 0.5777582 , 0.36248127],
         [0.28065434, 0.20310111, 0.18946402, 0.51135087, 0.33863264],
         ...,
         [0.5166867 , 0.49141726, 0.48271972, 0.02831001, 0.05074426],
         [0.6995667 , 0.31523436, 0.5162853 , 0.44742402, 0.549011  ],
         [0.16731434, 0.13127798, 0.5633259 , 0.17437308, 0.41280794]],

        [[0.31357077, 0.01648416, 0.12938903, 0.32192075, 

## Create a tensor with random values between 0 and 1 with shape [224, 224, 3]

In [31]:
tensor5 = generator.uniform(shape = (224,244,3))

In [32]:
tensor5

<tf.Tensor: shape=(224, 244, 3), dtype=float32, numpy=
array([[[0.2595333 , 0.17401075, 0.63436663],
        [0.7072829 , 0.17006588, 0.1570735 ],
        [0.9753814 , 0.7043445 , 0.60224986],
        ...,
        [0.14042306, 0.61405575, 0.6318302 ],
        [0.1321528 , 0.41065848, 0.42617893],
        [0.1599778 , 0.55356085, 0.6473173 ]],

       [[0.24767601, 0.8838495 , 0.38529837],
        [0.5330497 , 0.07397509, 0.49664772],
        [0.0631144 , 0.57254255, 0.9117892 ],
        ...,
        [0.9635122 , 0.14899194, 0.72784114],
        [0.26686883, 0.6642369 , 0.6813816 ],
        [0.35316288, 0.34701967, 0.58033717]],

       [[0.69697547, 0.90842354, 0.29152167],
        [0.5599538 , 0.36235142, 0.3102225 ],
        [0.5532409 , 0.7755734 , 0.43992472],
        ...,
        [0.32403874, 0.5787605 , 0.00249791],
        [0.34415054, 0.42498732, 0.15650249],
        [0.9033853 , 0.40391243, 0.6850661 ]],

       ...,

       [[0.8787434 , 0.15234041, 0.9761355 ],
        [0.68

In [34]:
tf.reduce_min(tensor5)

<tf.Tensor: shape=(), dtype=float32, numpy=2.9802322e-06>

In [35]:
tf.reduce_max(tensor5)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9999908>

In [36]:
tensor6 = generator.uniform(shape = (1,224,224,3))

In [37]:
tensor6

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[0.19889212, 0.12355423, 0.39414608],
         [0.7493892 , 0.363536  , 0.4461162 ],
         [0.41899848, 0.23648608, 0.78311384],
         ...,
         [0.9476334 , 0.47900867, 0.45631814],
         [0.23403072, 0.57125914, 0.9230622 ],
         [0.77669907, 0.3586861 , 0.7484398 ]],

        [[0.70363367, 0.35777354, 0.3577608 ],
         [0.55327535, 0.92525935, 0.37109983],
         [0.6317681 , 0.41825235, 0.15477705],
         ...,
         [0.13653553, 0.3997066 , 0.05515206],
         [0.24816716, 0.8838296 , 0.11379957],
         [0.36368108, 0.52155197, 0.15165949]],

        [[0.56727993, 0.28134727, 0.47661257],
         [0.9306692 , 0.35737348, 0.83955073],
         [0.80867887, 0.19369376, 0.6951271 ],
         ...,
         [0.09216952, 0.22912431, 0.01549304],
         [0.76439893, 0.4325874 , 0.7861464 ],
         [0.30149198, 0.5162314 , 0.27493942]],

        ...,

        [[0.41669655, 0.835876  , 

In [41]:
tensor6 = tf.squeeze(tensor6)

In [42]:
tensor6.shape

TensorShape([224, 224, 3])

## *Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.*

In [50]:
tensor7 = tf.constant(np.random.randint(0,10,size = [10,]))

In [51]:
tensor7

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([8, 5, 5, 7, 7, 4, 4, 1, 9, 1])>

## *Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value. One-hot encode the tensor you created in 9.*

In [54]:
one_hot_tensor7 = tf.one_hot(tensor7,depth = 10)

In [55]:
one_hot_tensor7

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>