## This Notebook contains the fundamentals of tensors using tensorflow

## Introduction to Tensors

In [ ]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.8.2


In [ ]:
# Create tensorf with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions of a tensor
scalar.ndim

0

In [ ]:
vector = tf.constant([10,10])

In [ ]:
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
vector1 = tf.constant([[10,10],[10,10]])

In [ ]:
vector1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 10],
       [10, 10]], dtype=int32)>

In [ ]:
vector1.ndim

2

In [ ]:
np.random.seed(0)
vector2 = tf.constant(np.random.randint(0,100,size = (7,3)))

In [ ]:
vector2

<tf.Tensor: shape=(7, 3), dtype=int64, numpy=
array([[44, 47, 64],
       [67, 67,  9],
       [83, 21, 36],
       [87, 70, 88],
       [88, 12, 58],
       [65, 39, 87],
       [46, 88, 81]])>

In [ ]:
vector2.ndim,vector2.shape

(2, TensorShape([7, 3]))

In [ ]:
matrix = tf.constant([[1.,2.],[2.,4.]],dtype = tf.float16)

In [ ]:
matrix

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[1., 2.],
       [2., 4.]], dtype=float16)>

In [ ]:
matrix.ndim

2

In [ ]:
tensor = tf.constant([
    [
        [1,2,3],
        [3,4,5],
    ],
    [
        [3,3,2],
        [3,1,3],
    ],
])

In [ ]:
tensor.ndim

3

In [ ]:
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [3, 4, 5]],

       [[3, 3, 2],
        [3, 1, 3]]], dtype=int32)>

In [ ]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])

In [ ]:
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Changing element of variable tensor
changeable_tensor[0].assign(9)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([9, 7], dtype=int32)>

## Random Tensors

In [ ]:
array= tf.random.Generator.from_seed(42)

In [ ]:
array = array.normal(shape = (3,2))
random2 = tf.random.Generator.from_seed(42)
random2 = random2.uniform(shape = (3,2))
random2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.7493447 , 0.73561966],
       [0.45230794, 0.49039817],
       [0.1889317 , 0.52027524]], dtype=float32)>

In [ ]:
array

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

## Shuffling Tensors

In [ ]:
not_shuffled = tf.constant([
  [10,7,3],
  [3,2,4],
  [2,6,7]
  ])

In [ ]:
not_shuffled.ndim

2

In [ ]:
not_shuffled

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[10,  7,  3],
       [ 3,  2,  4],
       [ 2,  6,  7]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffled,seed = 42)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[10,  7,  3],
       [ 3,  2,  4],
       [ 2,  6,  7]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffled,seed = 42)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[10,  7,  3],
       [ 3,  2,  4],
       [ 2,  6,  7]], dtype=int32)>

## Creating tensors from Numpy Array

In [ ]:
one_tensor = tf.Variable(np.ones(shape = (3,2)))

In [ ]:
one_tensor

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float64, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]])>

In [ ]:
tf.ones(shape = (4,7))

<tf.Tensor: shape=(4, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros(shape = (3,5))

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
numpy_A = np.arange(1,25,dtype = np.int32)

In [ ]:
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
tf.constant(numpy_A,shape = (1,3,8))

<tf.Tensor: shape=(1, 3, 8), dtype=int32, numpy=
array([[[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]]], dtype=int32)>

## Getting information from tensors

In [ ]:
rank_4_tensor = tf.zeros(shape = (2,3,4,5))

In [ ]:
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
print("Datatype of every element:",rank_4_tensor.dtype)
print("Number of dimensions:",rank_4_tensor.ndim)
print("Shape of tensor:",rank_4_tensor.shape)
print("Elements along the 0 axis:",rank_4_tensor.shape[0])
print("Elements along last axis:",rank_4_tensor.shape[-1])
print("Total elements:",tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions: 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along last axis: 5
Total elements: 120


## Indexing tensors

In [ ]:
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
rank_2_tensor = tf.constant([[
    10,7
],
[3,4]])

In [ ]:
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

## Tensor Operations

In [ ]:
tensor = tf.constant([[10,7],[3,4]])
tensor+=10
tensor


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
tf.add(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 27],
       [23, 24]], dtype=int32)>

In [ ]:
tf.multiply(tensor,20)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[400, 340],
       [260, 280]], dtype=int32)>

In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

## Matrix Multiplication

In [ ]:
tensor1 = tf.constant([[10,3],[3,10]])
tensor2 = tf.constant([[10,30],[20,40]])
tf.matmul(tensor1,tensor2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[160, 420],
       [230, 490]], dtype=int32)>

In [ ]:
tensor1@tensor2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[160, 420],
       [230, 490]], dtype=int32)>

In [ ]:
tensor1 = tf.constant([[1,2],[3,4],[5,6]])
tensor2 = tf.constant([[7,8],[9,10],[11,12]])
tf.matmul(tensor1,tf.reshape(tensor2,shape = (2,3)))


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
tf.matmul(tf.reshape(tensor1,shape = (2,3)),tensor2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [ ]:
tf.reshape(tensor1,shape = (2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [ ]:
## Performing the dot product on X and Y (requires X and Y to be transporsed)
tf.tensordot(tf.transpose(tensor1),tensor2,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
tf.matmul(tensor1,tf.transpose(tensor2))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
tf.matmul(tensor1,tf.reshape(tensor2,shape = (2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
tensor2,tf.reshape(tensor2,shape = (2,3)),tf.transpose(tensor2)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  9, 11],
        [ 8, 10, 12]], dtype=int32)>)

## Changing Data Type of Tensors

In [ ]:
B = tf.constant([1.3,int(-2),-3])

In [ ]:
B = tf.cast(B,dtype =tf.float64)

In [ ]:
B[2]

<tf.Tensor: shape=(), dtype=float64, numpy=-3.0>

In [ ]:
A = tf.constant([10,30,321])


In [ ]:
A = tf.cast(A,dtype = tf.float32)

In [ ]:
A

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 10.,  30., 321.], dtype=float32)>

## Aggregating Tensors

In [ ]:
D = tf.constant([-7,-10])

In [ ]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [ ]:
E = tf.constant(np.random.randint(0,100,size = 50))

In [ ]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [ ]:
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([37, 25, 77, 72,  9, 20, 80, 69, 79, 47, 64, 82, 99, 88, 49, 29, 19,
       19, 14, 39, 32, 65,  9, 57, 32, 31, 74, 23, 35, 75, 55, 28, 34,  0,
        0, 36, 53,  5, 38, 17, 79,  4, 42, 58, 31,  1, 65, 41, 57, 35])>

In [ ]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [ ]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2129>

## Find the positional maximum and minimum

In [ ]:
F = tf.random.uniform(shape = [50])

In [ ]:
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.21082067, 0.28333712, 0.77594316, 0.9453666 , 0.5092341 ,
       0.32357717, 0.4895481 , 0.5536635 , 0.13589144, 0.6397828 ,
       0.8512819 , 0.9877819 , 0.8912984 , 0.9957322 , 0.6264663 ,
       0.17389214, 0.8711132 , 0.91991997, 0.9921869 , 0.694232  ,
       0.11019814, 0.7238517 , 0.00857913, 0.9489007 , 0.59976137,
       0.7956233 , 0.61693656, 0.49520516, 0.6056323 , 0.40050173,
       0.6662054 , 0.8366209 , 0.60559154, 0.4572034 , 0.1768558 ,
       0.61131227, 0.05282521, 0.8881649 , 0.56118894, 0.867587  ,
       0.9224198 , 0.39844894, 0.48354876, 0.297966  , 0.07770407,
       0.14642358, 0.48481143, 0.391196  , 0.859535  , 0.9672327 ],
      dtype=float32)>

In [ ]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=13>

In [ ]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=22>

In [ ]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9957322>

In [ ]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.008579135>

In [ ]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9957322>

In [ ]:
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.008579135>

## Squeezing a tensor

In [ ]:
G = tf.constant(tf.random.uniform(shape = [50]),shape = (1,1,1,1,50))

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed.shape

TensorShape([50])

## One-hot encoding tensors

In [ ]:
some_list = [0,1,2,3]
tf.one_hot(some_list,depth = 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6588805 , 0.62492085, 0.9265852 , 0.2630849 , 0.48098052,
           0.85621834, 0.62951934, 0.5014883 , 0.12007904, 0.1276002 ,
           0.07869232, 0.50103307, 0.09289277, 0.2685566 , 0.05425882,
           0.00705111, 0.03443134, 0.940241  , 0.5707663 , 0.9311768 ,
           0.86820877, 0.5844003 , 0.83197165, 0.50582874, 0.36614835,
           0.5897851 , 0.36568522, 0.94432425, 0.5218499 , 0.21190643,
           0.33896482, 0.34093487, 0.51902115, 0.44229794, 0.33210003,
           0.69402087, 0.94461477, 0.14430702, 0.51976776, 0.00807083,
           0.3702141 , 0.86776865, 0.5102699 , 0.05055308, 0.8968177 ,
           0.7832171 , 0.5803968 , 0.8951006 , 0.64336085, 0.96328366]]]]],
      dtype=float32)>

In [ ]:
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
tf.sqrt(tf.cast(H,dtype = tf.float64))

<tf.Tensor: shape=(9,), dtype=float64, numpy=
array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])>

In [ ]:
tf.math.log(tf.cast(H,dtype = tf.float64))

<tf.Tensor: shape=(9,), dtype=float64, numpy=
array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])>

## Tensors and NumPy

In [ ]:
J = tf.constant(np.array([3.,7.,10.]))

In [ ]:
np.array(J)

array([ 3.,  7., 10.])

In [ ]:
J.numpy()[0]

3.0

In [ ]:
numpy_J = tf.constant(np.array([3.,7.,10.]))

In [ ]:
tensor_j = tf.constant([3.,7.,10.])

In [ ]:
numpy_J.dtype,tensor_j.dtype

(tf.float64, tf.float32)

In [ ]:
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]