## TensorFlow Fundamentals

## Introduction to Tensor

In [7]:
import tensorflow as tf
import numpy as np

In [8]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [9]:
scalar.ndim

0

In [10]:
vector = tf.constant([10,10])

In [11]:
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

## Changable Tensors

In [18]:
changeable_tensor = tf.Variable([10,7])

In [16]:
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>

In [17]:
changeable_tensor[1].assign(13)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([10, 13])>

## Random Tensors

In [20]:
array_generator_1  = tf.random.Generator.from_seed(42)

In [21]:
normal_sampling = array_generator_1.normal(shape = (3,2))

In [30]:
uniform_sampling = array_generator_1.uniform(shape = (3,2))

In [31]:
uniform_sampling

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.7647915 , 0.03845465],
       [0.8506975 , 0.20781887],
       [0.711869  , 0.8843919 ]], dtype=float32)>

In [32]:
normal_sampling

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>