## This Notebook contains the fundamentals of tensors using tensorflow

## Introduction to Tensors

In [1]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.8.2


In [2]:
# Create tensorf with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimensions of a tensor
scalar.ndim

0

In [4]:
vector = tf.constant([10,10])

In [5]:
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
vector.ndim

1

In [7]:
vector1 = tf.constant([[10,10],[10,10]])

In [8]:
vector1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 10],
       [10, 10]], dtype=int32)>

In [9]:
vector1.ndim

2

In [10]:
np.random.seed(0)
vector2 = tf.constant(np.random.randint(0,100,size = (7,3)))

In [11]:
vector2

<tf.Tensor: shape=(7, 3), dtype=int64, numpy=
array([[44, 47, 64],
       [67, 67,  9],
       [83, 21, 36],
       [87, 70, 88],
       [88, 12, 58],
       [65, 39, 87],
       [46, 88, 81]])>

In [12]:
vector2.ndim,vector2.shape

(2, TensorShape([7, 3]))

In [13]:
matrix = tf.constant([[1.,2.],[2.,4.]],dtype = tf.float16)

In [14]:
matrix

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[1., 2.],
       [2., 4.]], dtype=float16)>

In [15]:
matrix.ndim

2

In [16]:
tensor = tf.constant([
    [
        [1,2,3],
        [3,4,5],
    ],
    [
        [3,3,2],
        [3,1,3],
    ],
])

In [17]:
tensor.ndim

3

In [18]:
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [3, 4, 5]],

       [[3, 3, 2],
        [3, 1, 3]]], dtype=int32)>

In [19]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])

In [20]:
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [21]:
# Changing element of variable tensor
changeable_tensor[0].assign(9)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([9, 7], dtype=int32)>

## Random Tensors

In [22]:
array= tf.random.Generator.from_seed(42)

In [23]:
array = array.normal(shape = (3,2))
random2 = tf.random.Generator.from_seed(42)
random2 = random2.uniform(shape = (3,2))
random2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.7493447 , 0.73561966],
       [0.45230794, 0.49039817],
       [0.1889317 , 0.52027524]], dtype=float32)>

In [24]:
array

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

## Shuffling Tensors

In [25]:
not_shuffled = tf.constant([
  [10,7,3],
  [3,2,4],
  [2,6,7]
  ])

In [26]:
not_shuffled.ndim

2

In [27]:
not_shuffled

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[10,  7,  3],
       [ 3,  2,  4],
       [ 2,  6,  7]], dtype=int32)>

In [28]:
tf.random.shuffle(not_shuffled,seed = 42)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 2,  6,  7],
       [ 3,  2,  4],
       [10,  7,  3]], dtype=int32)>

In [29]:
tf.random.shuffle(not_shuffled,seed = 42)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 2,  6,  7],
       [ 3,  2,  4],
       [10,  7,  3]], dtype=int32)>

## Creating tensors from Numpy Array

In [30]:
one_tensor = tf.Variable(np.ones(shape = (3,2)))

In [31]:
one_tensor

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float64, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]])>

In [32]:
tf.ones(shape = (4,7))

<tf.Tensor: shape=(4, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [33]:
tf.zeros(shape = (3,5))

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [34]:
numpy_A = np.arange(1,25,dtype = np.int32)

In [35]:
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [36]:
tf.constant(numpy_A,shape = (1,3,8))

<tf.Tensor: shape=(1, 3, 8), dtype=int32, numpy=
array([[[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]]], dtype=int32)>

## Getting information from tensors

In [37]:
rank_4_tensor = tf.zeros(shape = (2,3,4,5))

In [38]:
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [39]:
print("Datatype of every element:",rank_4_tensor.dtype)
print("Number of dimensions:",rank_4_tensor.ndim)
print("Shape of tensor:",rank_4_tensor.shape)
print("Elements along the 0 axis:",rank_4_tensor.shape[0])
print("Elements along last axis:",rank_4_tensor.shape[-1])
print("Total elements:",tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions: 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along last axis: 5
Total elements: 120


## Indexing tensors

In [40]:
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [41]:
rank_2_tensor = tf.constant([[
    10,7
],
[3,4]])

In [42]:
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

## Tensor Operations

In [43]:
tensor = tf.constant([[10,7],[3,4]])
tensor+=10
tensor


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [44]:
tf.add(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 27],
       [23, 24]], dtype=int32)>

In [45]:
tf.multiply(tensor,20)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[400, 340],
       [260, 280]], dtype=int32)>

In [46]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

## Matrix Multiplication

In [47]:
tensor1 = tf.constant([[10,3],[3,10]])
tensor2 = tf.constant([[10,30],[20,40]])
tf.matmul(tensor1,tensor2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[160, 420],
       [230, 490]], dtype=int32)>

In [48]:
tensor1@tensor2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[160, 420],
       [230, 490]], dtype=int32)>

In [49]:
tensor1 = tf.constant([[1,2],[3,4],[5,6]])
tensor2 = tf.constant([[7,8],[9,10],[11,12]])
tf.matmul(tensor1,tf.reshape(tensor2,shape = (2,3)))


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [50]:
tf.matmul(tf.reshape(tensor1,shape = (2,3)),tensor2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [51]:
tf.reshape(tensor1,shape = (2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [55]:
## Performing the dot product on X and Y (requires X and Y to be transporsed)
tf.tensordot(tf.transpose(tensor1),tensor2,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [57]:
tf.matmul(tensor1,tf.transpose(tensor2))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [59]:
tf.matmul(tensor1,tf.reshape(tensor2,shape = (2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [60]:
tensor2,tf.reshape(tensor2,shape = (2,3)),tf.transpose(tensor2)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  9, 11],
        [ 8, 10, 12]], dtype=int32)>)

## Changing Data Type of Tensors

In [63]:
B = tf.constant([1.3,int(-2),-3])

In [71]:
B = tf.cast(B,dtype =tf.float64)

In [73]:
B[2]

<tf.Tensor: shape=(), dtype=float64, numpy=-3.0>

In [75]:
A = tf.constant([10,30,321])


In [76]:
A = tf.cast(A,dtype = tf.float32)

In [77]:
A

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 10.,  30., 321.], dtype=float32)>

## Aggregating Tensors

In [79]:
D = tf.constant([-7,-10])

In [80]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [81]:
E = tf.constant(np.random.randint(0,100,size = 50))

In [82]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [83]:
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([37, 25, 77, 72,  9, 20, 80, 69, 79, 47, 64, 82, 99, 88, 49, 29, 19,
       19, 14, 39, 32, 65,  9, 57, 32, 31, 74, 23, 35, 75, 55, 28, 34,  0,
        0, 36, 53,  5, 38, 17, 79,  4, 42, 58, 31,  1, 65, 41, 57, 35])>

In [84]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [85]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [86]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2129>

In [93]:
tf.math.reduce_std(E)

TypeError: ignored

## Find the positional maximum and minimum

In [94]:
F = tf.random.uniform(shape = [50])

In [95]:
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.61400175, 0.8336086 , 0.8646765 , 0.7963096 , 0.95017815,
       0.8115976 , 0.4750842 , 0.6040752 , 0.92809296, 0.49018848,
       0.40738344, 0.3613943 , 0.20811081, 0.6566447 , 0.42366695,
       0.84089494, 0.25961614, 0.89162683, 0.6830597 , 0.711856  ,
       0.89614093, 0.13287127, 0.5015093 , 0.37260783, 0.8244382 ,
       0.60663855, 0.95095634, 0.30530035, 0.22515869, 0.8105384 ,
       0.06830752, 0.7460948 , 0.68806016, 0.87940526, 0.9723505 ,
       0.39649522, 0.2964791 , 0.14433444, 0.7944156 , 0.1828928 ,
       0.2925794 , 0.7307867 , 0.05220115, 0.9972484 , 0.50675154,
       0.85746837, 0.4152751 , 0.24867225, 0.50231683, 0.3366152 ],
      dtype=float32)>

In [96]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=43>

In [97]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [98]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9972484>

In [99]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.05220115>

In [100]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9972484>

In [101]:
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.05220115>

## Squeezing a tensor