In [176]:
import numpy as np
import pandas as pd
import PIL as pi

## DataTypes and Attributes 

In [7]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [8]:
type(a1)

numpy.ndarray

In [9]:
a2 = np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
a3 = np.array([[[1,2,3],
                [4.5,5.6,6],
                [0,0,0],
               ]])

In [11]:
a3

array([[[1. , 2. , 3. ],
        [4.5, 5.6, 6. ],
        [0. , 0. , 0. ]]])

In [12]:
a1.shape

(3,)

In [13]:
a3.shape

(1, 3, 3)

In [14]:
a2.shape

(2, 3)

In [15]:
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [16]:
a3.dtype

dtype('float64')

In [17]:
a1.size

3

In [18]:
a3.size

9

# Create a DataFrame from a NumPy array

In [19]:
import pandas as pd
df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

In [20]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [21]:
sample_array.dtype

dtype('int32')

In [22]:
ones = np.ones((3,2))

In [23]:
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [24]:
zeroes = np.zeros((2,3))

In [25]:
zeroes

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
rarray = np.arange(0,10,2)
rarray

array([0, 2, 4, 6, 8])

In [27]:
random_array = np.random.randint(0,10,size=(3,5))
random_array

array([[8, 9, 1, 0, 3],
       [8, 6, 7, 5, 7],
       [2, 4, 7, 9, 7]])

In [28]:
random_array.size

15

In [29]:
np.random.random((5,3))

array([[0.70681929, 0.89299997, 0.94654121],
       [0.50291016, 0.82501137, 0.59729094],
       [0.35804655, 0.56914046, 0.0770394 ],
       [0.16853828, 0.04998737, 0.39139846],
       [0.51346904, 0.8676198 , 0.47796426]])

In [30]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.16447774, 0.69513508, 0.82324214],
       [0.03231632, 0.53223156, 0.71034633],
       [0.62888972, 0.98719534, 0.55629132],
       [0.78368843, 0.67169301, 0.26491678],
       [0.82500003, 0.40429754, 0.02895129]])

## Pseudo-Random Numbers

In [31]:
np.random.seed(seed = 42)
random_array = np.random.randint(10,size = (5,3))

In [32]:
random_array

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7],
       [4, 3, 7],
       [7, 2, 5]])

## Viewing Arrays and Matrices

In [33]:
a2[0][0]

1

In [34]:
a3.shape

(1, 3, 3)

In [35]:
a3[:2,:2,:2]

array([[[1. , 2. ],
        [4.5, 5.6]]])

In [36]:
a4 = np.random.randint(10,size = (3,4,5))

In [37]:
a3.shape

(1, 3, 3)

In [38]:
a4.shape,a4.ndim

((3, 4, 5), 3)

In [39]:
a4

array([[[4, 1, 7, 5, 1],
        [4, 0, 9, 5, 8],
        [0, 9, 2, 6, 3],
        [8, 2, 4, 2, 6]],

       [[4, 8, 6, 1, 3],
        [8, 1, 9, 8, 9],
        [4, 1, 3, 6, 7],
        [2, 0, 3, 1, 7]],

       [[3, 1, 5, 5, 9],
        [3, 5, 1, 9, 1],
        [9, 3, 7, 6, 8],
        [7, 4, 1, 4, 7]]])

## Manipulating Array

In [40]:
a1

array([1, 2, 3])

In [41]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [42]:
a1+ones

array([2., 3., 4.])

In [43]:
a1-ones

array([0., 1., 2.])

In [44]:
ones-a1

array([ 0., -1., -2.])

In [45]:
a1*ones

array([1., 2., 3.])

In [46]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
a1*a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [48]:
a2*a1

array([[ 1,  4,  9],
       [ 4, 10, 18]])

## Aggregation

In [49]:
list1 = [1,2,3]
type(list1)

list

a1

In [50]:
a1

array([1, 2, 3])

In [51]:
np.sum(a1)

6

In [52]:
np.sum(a2)

21

In [53]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
np.sum(a3)

22.1

In [55]:
np.mean(a2)

3.5

In [56]:
np.var(a2)

2.9166666666666665

In [57]:
np.sqrt(np.var(a2))

1.707825127659933

## Standard Deviation and Variance

In [58]:
high_var = np.array([1,100,200,300,4000,5000])
low_var = np.array([2,4,6,8,10])

## Reshaping and Transposing

In [59]:
a3.shape

(1, 3, 3)

In [60]:
a2*a3

ValueError: operands could not be broadcast together with shapes (2,3) (1,3,3) 

In [71]:
a2.reshape(2,3,1).shape

(2, 3, 1)

In [72]:
a3.shape

(1, 3, 3)

In [74]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [94]:
a2 = a2.reshape(2,1,3)

In [95]:
a2*a3

array([[[ 1. ,  4. ,  9. ],
        [ 4.5, 11.2, 18. ],
        [ 0. ,  0. ,  0. ]],

       [[ 4. , 10. , 18. ],
        [18. , 28. , 36. ],
        [ 0. ,  0. ,  0. ]]])

In [97]:
a3.T

array([[[1. ],
        [4.5],
        [0. ]],

       [[2. ],
        [5.6],
        [0. ]],

       [[3. ],
        [6. ],
        [0. ]]])

In [98]:
a2

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [99]:
a2.T

array([[[1, 4]],

       [[2, 5]],

       [[3, 6]]])

## Dot Product

In [100]:
a3

array([[[1. , 2. , 3. ],
        [4.5, 5.6, 6. ],
        [0. , 0. , 0. ]]])

In [101]:
a3.shape

(1, 3, 3)

In [102]:
a3.T.shape

(3, 3, 1)

In [105]:
np.random.seed(0)
mat1 = np.random.randint(10,size=(5,3))
mat2 = np.random.randint(10,size=(5,3))

In [107]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [108]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [110]:
np.dot(mat1,mat2.T)

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

In [163]:
np.random.seed(0)
sales_amount = np.random.randint(20,size = (7,3))
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7],
       [14, 17,  5],
       [13,  8,  9]])

In [164]:
weekly_sales = pd.DataFrame(sales_amount,index = ['Mon','Tue','Wed','Thu','Fri','Sat','Sun'],columns = ['Almond Butter','Peanut Butter','Cashew Butter'])

In [165]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon             12             15              0
Tue              3              3              7
Wed              9             19             18
Thu              4              6             12
Fri              1              6              7
Sat             14             17              5
Sun             13              8              9

In [166]:
price = np.array([10,8,12])

In [139]:
price.reshape(1,3)

array([[10,  8, 12]])

In [167]:
butter_prices = pd.DataFrame(price.reshape(1,3),index = ["Price"],columns = ['Almond Butter','Peanut Butter','Cashew Butter'])

In [170]:
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [171]:
total_sales = butter_prices.dot(weekly_sales.T)

In [154]:
total_sales.T

Price
0    240
1    138
2    458
3    232
4    142
5    336
6    302

In [172]:
total_sales.shape

(1, 7)

In [173]:
weekly_sales["Total"] = total_sales.T

In [174]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter  Total
Mon             12             15              0    240
Tue              3              3              7    138
Wed              9             19             18    458
Thu              4              6             12    232
Fri              1              6              7    142
Sat             14             17              5    336
Sun             13              8              9    302

## Images and Numpy

<img src = '../images/numpy-panda.png'/>

In [178]:
from matplotlib.image import imread

In [184]:
panda = imread("../images/numpy-panda.png")

In [185]:
panda.size

24465000

In [186]:
panda.shape

(2330, 3500, 3)

In [187]:
panda.ndim

3