In [13]:
import numpy as np

## DataTypes and Attributes 

In [14]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [15]:
type(a1)

numpy.ndarray

In [16]:
a2 = np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
a3 = np.array([[[1,2,3],
                [4.5,5.6,6],
                [0,0,0],
               ]])

In [18]:
a3

array([[[1. , 2. , 3. ],
        [4.5, 5.6, 6. ],
        [0. , 0. , 0. ]]])

In [19]:
a1.shape

(3,)

In [20]:
a3.shape

(1, 3, 3)

In [21]:
a2.shape

(2, 3)

In [22]:
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [23]:
a3.dtype

dtype('float64')

In [24]:
a1.size

3

In [25]:
a3.size

9

# Create a DataFrame from a NumPy array

In [26]:
import pandas as pd
df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

In [27]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [28]:
sample_array.dtype

dtype('int32')

In [29]:
ones = np.ones((3,2))

In [30]:
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [31]:
zeroes = np.zeros((2,3))

In [32]:
zeroes

array([[0., 0., 0.],
       [0., 0., 0.]])

In [33]:
rarray = np.arange(0,10,2)
rarray

array([0, 2, 4, 6, 8])

In [34]:
random_array = np.random.randint(0,10,size=(3,5))
random_array

array([[4, 1, 7, 5, 1],
       [4, 0, 9, 5, 8],
       [0, 9, 2, 6, 3]])

In [35]:
random_array.size

15

In [36]:
np.random.random((5,3))

array([[0.59241457, 0.04645041, 0.60754485],
       [0.17052412, 0.06505159, 0.94888554],
       [0.96563203, 0.80839735, 0.30461377],
       [0.09767211, 0.68423303, 0.44015249],
       [0.12203823, 0.49517691, 0.03438852]])

In [37]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.9093204 , 0.25877998, 0.66252228],
       [0.31171108, 0.52006802, 0.54671028],
       [0.18485446, 0.96958463, 0.77513282],
       [0.93949894, 0.89482735, 0.59789998],
       [0.92187424, 0.0884925 , 0.19598286]])

## Pseudo-Random Numbers

In [38]:
np.random.seed(seed = 42)
random_array = np.random.randint(10,size = (5,3))

In [39]:
random_array

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7],
       [4, 3, 7],
       [7, 2, 5]])

## Viewing Arrays and Matrices

In [43]:
a2[0][0]

1

In [45]:
a3.shape

(1, 3, 3)

In [46]:
a3[:2,:2,:2]

array([[[1. , 2. ],
        [4.5, 5.6]]])

In [47]:
a4 = np.random.randint(10,size = (3,4,5))

In [49]:
a3.shape

(1, 3, 3)

In [51]:
a4.shape,a4.ndim

((3, 4, 5), 3)

In [52]:
a4

array([[[4, 1, 7, 5, 1],
        [4, 0, 9, 5, 8],
        [0, 9, 2, 6, 3],
        [8, 2, 4, 2, 6]],

       [[4, 8, 6, 1, 3],
        [8, 1, 9, 8, 9],
        [4, 1, 3, 6, 7],
        [2, 0, 3, 1, 7]],

       [[3, 1, 5, 5, 9],
        [3, 5, 1, 9, 1],
        [9, 3, 7, 6, 8],
        [7, 4, 1, 4, 7]]])

## Manipulating Array