In [1]:
import numpy as np

## DataTypes and Attributes 

In [2]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [14]:
a2 = np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
a3 = np.array([[[1,2,3],
                [4.5,5.6,6],
                [0,0,0],
               ]])

In [9]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [11]:
a1.shape

(3,)

In [12]:
a3.shape

(1, 3, 3)

In [15]:
a2.shape

(2, 3)

In [18]:
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [22]:
a3.dtype

dtype('float64')

In [23]:
a1.size

3

In [24]:
a3.size

9

# Create a DataFrame from a NumPy array

In [25]:
import pandas as pd
df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

In [26]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [27]:
sample_array.dtype

dtype('int32')

In [32]:
ones = np.ones((3,2))

In [34]:
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [39]:
zeroes = np.zeros((2,3))

In [40]:
zeroes

array([[0., 0., 0.],
       [0., 0., 0.]])

In [42]:
rarray = np.arange(0,10,2)
rarray

array([0, 2, 4, 6, 8])

In [45]:
random_array = np.random.randint(0,10,size=(3,5))
random_array

array([[5, 0, 1, 1, 5],
       [4, 1, 0, 7, 4],
       [0, 3, 0, 5, 9]])

In [46]:
random_array.size

15

In [47]:
np.random.random((5,3))

array([[0.88066357, 0.24628322, 0.90749972],
       [0.54446243, 0.25190623, 0.07838813],
       [0.8171591 , 0.50815916, 0.82731671],
       [0.77055133, 0.47277149, 0.50140404],
       [0.57314476, 0.91190237, 0.59260062]])

In [49]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.90145398, 0.04587929, 0.87971877],
       [0.70380566, 0.51463362, 0.1477182 ],
       [0.44567476, 0.8406291 , 0.24564389],
       [0.46990454, 0.27389465, 0.43404077],
       [0.94419101, 0.63969666, 0.71714822]])