In [1]:
import numpy as np

## DataTypes and Attributes 

In [2]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a3 = np.array([[[1,2,3],
                [4.5,5.6,6],
                [0,0,0],
               ]])

In [6]:
a3

array([[[1. , 2. , 3. ],
        [4.5, 5.6, 6. ],
        [0. , 0. , 0. ]]])

In [7]:
a1.shape

(3,)

In [8]:
a3.shape

(1, 3, 3)

In [9]:
a2.shape

(2, 3)

In [10]:
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [11]:
a3.dtype

dtype('float64')

In [12]:
a1.size

3

In [13]:
a3.size

9

# Create a DataFrame from a NumPy array

In [14]:
import pandas as pd
df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

In [15]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [16]:
sample_array.dtype

dtype('int32')

In [17]:
ones = np.ones((3,2))

In [18]:
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [19]:
zeroes = np.zeros((2,3))

In [20]:
zeroes

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
rarray = np.arange(0,10,2)
rarray

array([0, 2, 4, 6, 8])

In [22]:
random_array = np.random.randint(0,10,size=(3,5))
random_array

array([[9, 2, 9, 5, 4],
       [9, 2, 7, 5, 6],
       [1, 0, 2, 0, 4]])

In [23]:
random_array.size

15

In [24]:
np.random.random((5,3))

array([[0.0033957 , 0.12257736, 0.03584393],
       [0.6965155 , 0.90608198, 0.3428561 ],
       [0.07382774, 0.92696888, 0.41092266],
       [0.23653897, 0.89700564, 0.28726843],
       [0.93582941, 0.85249398, 0.11381215]])

In [25]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.59105344, 0.70185725, 0.2525207 ],
       [0.51772882, 0.26419708, 0.42419883],
       [0.90603939, 0.2000402 , 0.20842202],
       [0.10424531, 0.03556439, 0.31105371],
       [0.59431158, 0.63049838, 0.90386924]])

## Pseudo-Random Numbers

In [26]:
np.random.seed(seed = 42)
random_array = np.random.randint(10,size = (5,3))

In [27]:
random_array

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7],
       [4, 3, 7],
       [7, 2, 5]])

## Viewing Arrays and Matrices

In [28]:
a2[0][0]

1

In [29]:
a3.shape

(1, 3, 3)

In [30]:
a3[:2,:2,:2]

array([[[1. , 2. ],
        [4.5, 5.6]]])

In [31]:
a4 = np.random.randint(10,size = (3,4,5))

In [32]:
a3.shape

(1, 3, 3)

In [33]:
a4.shape,a4.ndim

((3, 4, 5), 3)

In [52]:
a4

array([[[4, 1, 7, 5, 1],
        [4, 0, 9, 5, 8],
        [0, 9, 2, 6, 3],
        [8, 2, 4, 2, 6]],

       [[4, 8, 6, 1, 3],
        [8, 1, 9, 8, 9],
        [4, 1, 3, 6, 7],
        [2, 0, 3, 1, 7]],

       [[3, 1, 5, 5, 9],
        [3, 5, 1, 9, 1],
        [9, 3, 7, 6, 8],
        [7, 4, 1, 4, 7]]])

## Manipulating Array

In [34]:
a1

array([1, 2, 3])

In [38]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [39]:
a1+ones

array([2., 3., 4.])

In [40]:
a1-ones

array([0., 1., 2.])

In [41]:
ones-a1

array([ 0., -1., -2.])

In [42]:
a1*ones

array([1., 2., 3.])

In [43]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
a1*a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [45]:
a2*a1

array([[ 1,  4,  9],
       [ 4, 10, 18]])

## Aggregation

In [46]:
list1 = [1,2,3]
type(list1)

list

a1

In [47]:
a1

array([1, 2, 3])

In [48]:
np.sum(a1)

6

In [49]:
np.sum(a2)

21

In [50]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
np.sum(a3)

22.1

In [52]:
np.mean(a2)

3.5

In [53]:
np.var(a2)

2.9166666666666665

In [54]:
np.sqrt(np.var(a2))

1.707825127659933

## Standard Deviation and Variance

In [56]:
high_var = np.array([1,100,200,300,4000,5000])
low_var = np.array([2,4,6,8,10])